// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMvA2NWLzddmPZjsznyS25qZdI1UWG3OI',
    appId: '1:369850035035:web:07dc1c274ed4e9c4aec87e',
    messagingSenderId: '369850035035',
    projectId: 'auction-manager-52959',
    authDomain: 'auction-manager-52959.firebaseapp.com',
    storageBucket: 'auction-manager-52959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDUvc9L8WUmaxjFybao37qbcXQZaX1oPw',
    appId: '1:369850035035:android:b1f45c4ed80a121baec87e',
    messagingSenderId: '369850035035',
    projectId: 'auction-manager-52959',
    storageBucket: 'auction-manager-52959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUvc9L8WUmaxjFybao37qbcXQZaX1oPw',
    appId: '1:369850035035:ios:b1f45c4ed80a121baec87e',
    messagingSenderId: '369850035035',
    projectId: 'auction-manager-52959',
    storageBucket: 'auction-manager-52959.firebasestorage.app',
    iosBundleId: 'com.auctionmanager.auctionManager',
  );
}
